---
title: "Practical Exam in CS 101"
author: "Austine John Calatana BSIT 2-B"
date: "2023-11-14"
output: html_document
---

``` {r num 1}
mtcars
```
``` {r num2}
num_observations <- nrow(mtcars)
num_columns <- ncol(mtcars)
column_names <- colnames(mtcars)

cat("Number of observations:", num_observations, "\n")
cat("Number of columns:", num_columns, "\n")
cat("Column names:", column_names, "\n")
```
``` {r mum3}
num_summary <- summary(mtcars)

structure_info <- str(mtcars)

print("Summary of Numerical Variables:")
print(num_summary)

print("\nStructure of Variables:")
print(structure_info)

```

``` {r num4}
install.packages("ggplot2")
library(ggplot2)


data <- data.frame(transmission = c("Automatic", "Manual", "Automatic", "Automatic", "Manual", "Manual", "Automatic", "Automatic", "Manual"))


ggplot(data, aes(x = transmission)) +
  geom_bar(fill = "skyblue", color = "black") +
  labs(title = "Distribution of Transmission Types",
       x = "Transmission Type",
       y = "Count")

```

``` {r num5}
max_mpg_index <- which.max(mtcars$mpg)
model_highest_mpg <- mtcars$model[max_mpg_index]


max_hp_index <- which.max(mtcars$hp)
model_highest_hp <- mtcars$model[max_hp_index]

cat("Model with the highest mpg:", model_highest_mpg, "\n")
cat("Car model with the highest horsepower:", model_highest_hp, "\n")
```

``` {r num6}
eight_cyl_cars <- mtcars[mtcars$cyl == 8, ]

write.csv(eight_cyl_cars, file = "newCar.csv", row.names = FALSE)

head(eight_cyl_cars, 2)

```


